[build]
builder = "nixpacks"
rootDirectory = "backend"

[providers.node]
nodeVersion = "22"  # قمنا بتغييرها هنا أيضاً إلى 22 لتتطابق مع المتغيرات

[setup]
aptPackages = ["chromium"]

[phases.build]
cmds = ["npm install"]

[phases.start]
cmd = "node server.js"