[build]
builder = "nixpacks"
rootDirectory = "backend"

[providers.node]
nodeVersion = "22"

[setup]
aptPackages = ["chromium"]

[phases.build]
cmds = ["npm install"]

[phases.start]
cmd = "node server.js"

[deploy]
port = 8080       # أضفنا هذا السطر لإجبار ريلوي على فتح منفذ ويب عام
restartPolicy = "on-failure"